pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Test') {
            steps {
                sh 'npm test'
            }
        }
    }
    post {
        always {
            script {
                def buildStatus = currentBuild.result ?: 'SUCCESS'
                def developer = "${env.BUILD_USER}"
                sh "node ../contracts/logBuild.js ${currentBuild.id} ${buildStatus} ${developer}"
            }
        }
    }
}

